# Generated by Django 5.0.7 on 2024-07-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkchain',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='networkchain',
            name='product',
        ),
    ]
