# Generated by Django 5.0.7 on 2024-07-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_networkchain_contacts_networkchain_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkchain',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='networkchain',
            name='products',
        ),
        migrations.AddField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.networkchain', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.networkchain', verbose_name='Продавец'),
        ),
    ]
